# Generated by Django 5.0.6 on 2024-05-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('Compra', 'Compra'), ('Venta', 'Venta')], max_length=7),
        ),
    ]
