# Generated by Django 5.0.6 on 2024-05-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('Compra', 'Compra'), ('Venta', 'Venta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='denominacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.denominacion'),
        ),
        migrations.AddField(
            model_name='denominacion',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.moneda'),
        ),
    ]
