# Generated by Django 5.0.6 on 2024-05-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_denominacion_moneda_alter_movimiento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.moneda'),
        ),
    ]
